import 'server-only'; import {db} from './db'; import {decrypt,encrypt} from './crypto';
const BASE='https://api.spotify.com/v1';
export const redirectUri=()=>process.env.SPOTIFY_REDIRECT_URI||'http://127.0.0.1:3000/api/auth/callback/spotify';
function credentials(){const id=process.env.SPOTIFY_CLIENT_ID,secret=process.env.SPOTIFY_CLIENT_SECRET;if(!id||!secret)throw new Error('Spotify credentials are not configured');return {id,secret}}
async function token(body:URLSearchParams){const {id,secret}=credentials();const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`Spotify authorization failed (${r.status})`);return r.json()}
export async function exchange(code:string){return token(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirectUri()}))}
export async function roomToken(room:any){try{if(room.expires_at>Date.now()+60000)return decrypt(room.access_token);const fresh=await token(new URLSearchParams({grant_type:'refresh_token',refresh_token:await decrypt(room.refresh_token)}));if(!fresh.access_token||!fresh.expires_in)throw new Error('Incomplete refresh response');db.prepare('UPDATE rooms SET access_token=?, refresh_token=?, expires_at=? WHERE id=?').run(await encrypt(fresh.access_token),fresh.refresh_token?await encrypt(fresh.refresh_token):room.refresh_token,Date.now()+fresh.expires_in*1000,room.id);return fresh.access_token as string}catch{throw new Error('The room’s Spotify connection is no longer valid; the host must start a new room')}}
export async function spotify(path:string,access:string,init:RequestInit={},attempt=0):Promise<any>{const r=await fetch(`${BASE}${path}`,{...init,headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json',...init.headers},cache:'no-store'});if(r.status===429){const retryAfter=Math.max(1,Number(r.headers.get('retry-after')||1));if(attempt<2&&retryAfter<=5){await new Promise(x=>setTimeout(x,retryAfter*1000));return spotify(path,access,init,attempt+1)}throw new Error(`Spotify rate limit reached; retry in ${retryAfter} seconds`)}if(r.status===204)return null;if(!r.ok)throw new Error(`Spotify API ${r.status}: ${(await r.text()).slice(0,180)}`);return r.json()}
export const scopes=['user-read-private','playlist-modify-private','playlist-modify-public','user-read-playback-state','user-modify-playback-state'];
